management:
  health:
    diskspace:
      enabled: true
    default:
      enabled: true
    db:
      enabled: true
  servlet:
    context-path: /manage

spa:
  default-file: /dist/index.html5

spring:
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: false

  application:
    name: wms

  sql:
    init:
      mode: always
      schema: classpath:schema.sql
      data: classpath:data.sql
      encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://wms.cbgii0wwoaik.ap-northeast-2.rds.amazonaws.com:3306/wms
    username: admin
    password: ${secret.mysql.password}

  data:
    redis:
      host: 172.31.43.48
      port: 6379
      password: ${secret.redis.password}
    web:
      pageable:
        default-page-size: 10

logging:
  level:
    org:
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE
      spring.boot: DEBUG
      spring.security: DEBUG
      spring.web: DEBUG
      apache.tiles: INFO
      spring.mail: DEBUG
    root: INFO

server:
  error:
    include-stacktrace: never
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
    context-path: /api
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

build:
  date: "@build.date@"

#springfox:
#  documentation:
#    swagger:
#      use-model-v3: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${secret.cloud.accessKey}
      secretKey: ${secret.cloud.secretKey}
    s3:
      bucket: wms

jwt:
  refresh-expired-in: '1296000000'  # Refresh Token 만료 시간 (15일)
  access-expired-in: '18000000'      # Access Token 만료 시간 (5시간)
  cookieName: refreshToken
  secret: ${secret-jwt.secret}

mybatis:
  mapper-locations: classpath:/mybatis/**/*.xml
  type-aliases-package: com.example.wms.**.domain
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar
    call-setters-on-nulls: true
    auto-mapping-unknown-column-behavior: none
