version: '3'

services:
  spring-wms-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-wms-green
    ports:
      - "8011:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - servernetwork
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - spring-wms-green
    networks:
      - servernetwork
    restart: unless-stopped

networks:
  servernetwork:
    external: true