version: '3'
services:
  spring-wms-blue:
    image: backend:${BUILD_NUMBER}
    container_name: spring-wms-blue
    ports:
      - "8011:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - servernetwork

networks:
  servernetwork:
    external: true
