version: '3'
services:
  backend:
    build: .
    ports:
      - "8012:80"
    container_name: spring-wms-green
    environment:
      - TZ=Asia/Seoul
    networks:
      - servernetwork
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일 마운트
    networks:
      - servernetwork  # Nginx를 동일한 네트워크에 연결
    depends_on:
      - backend

networks:
  servernetwork:
    external: true
    driver: bridge
