version: '3'
services:
  backend:
    build: ..
    ports:
      - "8112:80"
    container_name: spring-wms-green
    environment:
      - TZ=Asia/Seoul
    networks:
      - servernetwork
    volumes:
      - ./app:/app  # 백엔드 애플리케이션 소스코드를 컨테이너 내부로 매핑
      - /var/run/docker.sock:/var/run/docker.sock  # DooD 방식으로 Docker 소켓 공유

networks:
  servernetwork:
    external: true
    driver: bridge
