version: '3'
services:
  backend:
    build: .
    ports:
      - "8011:80"
    container_name: spring-wms-blue
    environment:
      - TZ=Asia/Seoul
    networks:
      - servernetwork
    volumes:
      - ./app:/app  # 백엔드 애플리케이션 소스코드를 컨테이너 내부로 매핑
      - /var/run/docker.sock:/var/run/docker.sock  # DooD 방식으로 Docker 소켓 공유

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일 마운트
    networks:
      - servernetwork  # Nginx를 동일한 네트워크에 연결
    depends_on:
      - backend

networks:
  servernetwork:
    external: true
    driver: bridge
