# docker-compose.green.yml
version: '3'
services:
  spring-wms-green:
    image: backend:${BUILD_NUMBER}
    container_name: spring-wms-green
    ports:
      - "8012:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - servernetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "redis:172.19.0.3"
networks:
  servernetwork:
    driver: bridge