version: '3'

services:
  spring-wms-blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-wms-blue
    ports:
      - "8012:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - servernetwork
    restart: unless-stopped

networks:
  servernetwork:
    external: true