version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    container_name: spring-wms-blue
    environment:
      - TZ=Asia/Seoul
    networks:
      - servernetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - servernetwork
    depends_on:
      - backend

networks:
  servernetwork:
    external: true