version: '3'
services:
  spring-wms-blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-wms-blue
    ports:
      - "8011:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=redis-container
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - servernetwork
    depends_on:
      - redis-container

  redis-container:
    image: redis:6
    container_name: redis-container
    ports:
      - "6379:6379"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    networks:
      - servernetwork
    restart: unless-stopped

networks:
  servernetwork:
    external: true