version: '3'
services:
  spring-wms-blue:
    image: backend:${BUILD_NUMBER}
    container_name: spring-wms-blue
    ports:
      - "8011:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=redis

    networks:
      - servernetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  servernetwork:
    external: true