version: '3'
services:
  spring-wms-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-wms-green
    ports:
      - "8012:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=redis-container
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - servernetwork
    depends_on:
      - redis-container
    restart: unless-stopped

  redis-container:
    image: redis:6
    container_name: redis-container
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${secret.redis.password}
    environment:
      - REDIS_PASSWORD=${secret.redis.password}
    networks:
      - servernetwork
    restart: unless-stopped

networks:
  servernetwork:
    external: true